import { Product } from '@/models/homepage-model';

export async function GET(request: Request) {
  const data: Product[] = [
    {
      id: 1,
      name: 'Breed Dry Dog Food',
      price: 100,
      image: 'dogfood.png',
      rating: 3,
      reviews: 35,
      isNew: false,
      colors: [],
    },
    {
      id: 2,
      name: 'CANON EOS DSLR Camera',
      price: 360,
      image: 'camera.png',
      rating: 4,
      reviews: 95,
      isNew: false,
      colors: [],
    },
    {
      id: 3,
      name: 'ASUS FHD Gaming Laptop',
      price: 700,
      image: 'laptop.png',
      rating: 5,
      reviews: 325,
      isNew: false,
      colors: [],
    },
    {
      id: 4,
      name: 'Curology Product Set',
      price: 500,
      image: 'curology.png',
      rating: 4,
      reviews: 145,
      isNew: false,
      colors: [],
    },
    {
      id: 5,
      name: 'Kids Electric Car',
      price: 960,
      image: 'car.png',
      rating: 5,
      reviews: 65,
      isNew: true,
      colors: ['red', 'black'],
    },
    {
      id: 6,
      name: 'Jr. Zoom Soccer Cleats',
      price: 1160,
      image: 'shoes.png',
      rating: 5,
      reviews: 35,
      isNew: false,
      colors: ['yellow', 'red'],
    },
    {
      id: 7,
      name: 'GP11 Shooter USB Gamepad',
      price: 660,
      image: 'controller.png',
      rating: 4.5,
      reviews: 55,
      isNew: true,
      colors: ['red', 'black'],
    },
    {
      id: 8,
      name: 'Quilted Satin Jacket',
      price: 660,
      image: 'jacket.png',
      rating: 4.5,
      reviews: 55,
      isNew: false,
      colors: ['green', 'red'],
    },
  ];

  return Response.json({ data });
}
