import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import UserPageLayout from "@/ui/layouts/UserLayout";

export const metadata: Metadata = {
    title: "Ecommerce app v2",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <UserPageLayout>
                    {children}
                </UserPageLayout>
            </body>
        </html>
    );
}
