import type { Metadata } from "next";
import UserLayout from "@/layout/UserLayout";

export const metadata: Metadata = {
    title: "Ecommerce app v2",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <UserLayout>
                {children}
            </UserLayout>
        </html>
    );
}