spring:
  application:
    name: user
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5435/user_db
    username: user_dev
    password: user-microservice

server:
  port: 8001

infrastructure:
  jwt:
    secret: user-secret
    expiration-time: 604800000L



