spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5435/user_db
    username: user_dev
    password: user-microservice
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      group-id: test-group

server:
  port: 8001

infrastructure:
  jwt:
    secret: and0LXNlY3JldCZqd3Qtc2VjcmV0Jmp3dC1zZWNyZXQmand0LXNlY3JldA==
