external:
  microservice:
    user:
      url: http://localhost:8001
      uri:
        token-verify: /services/jwt-decode
      timeout: 5000
      feature-flags:
        enable-logging: true

spring:
  application:
    name: product
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5436/product_db
    username: product_dev
    password: product-microservice
  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      group-id: test-group

server:
  port: 8000

logging:
  level:
    org:
      springframework:
        security: DEBUG